name: Greeting Workflow
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install pytest
        run : pip install pytest
        
      - name: Run Python Tests
        run: python3 test_calc.py
        

      - name: Run a greeting
        run: echo "The CI pipeline has successfully started!"
